trigger:
  - main

pool:
  name: 'Mylocalagent'   # Use the pool where your self-hosted agent is registered

steps:
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'ASoCConnect'
    applications: 'bc39ab99-5c56-4548-b3ed-4f11efc1cba0'
    scanname: 'RVPTest'
    scantype: 'dynamic'
    dynamicType: 'DAST'
    scanURL: 'https://demo.testfire.net'
    network: 'public'
    intervention: false
